<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="user-Latitude-3420" failures="1" tests="4" name="Realme" time="47.165" errors="0" timestamp="2023-10-29T17:38:37 IST">
  <testcase classname="com.qa.tests.LoginTests" name="emptyUserName" time="7.399"/>
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserName" time="7.849"/>
  <testcase classname="com.qa.tests.LoginTests" name="lockedUserSoftAssert" time="9.175">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Provided credentials do not match any user in this service.] but found [Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Provided credentials do not match any user in this service.] but found [Sorry, this user has been locked out.]
at com.qa.tests.LoginTests.lockedUserSoftAssert(LoginTests.java:111)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- lockedUserSoftAssert -->
  <testcase classname="com.qa.tests.LoginTests" name="validUserName" time="8.076"/>
</testsuite> <!-- Realme -->
